### 데이터 하나로 통합하기

In [22]:
import json
import pandas as pd

with open('../Datasets/train.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

In [23]:
train_data = pd.DataFrame(json_data)
train_data = train_data.drop(['tags', 'plylst_title', 'updt_date'], axis=1)
train_data = train_data.explode('songs')
train_data.rename(columns={'songs':'song_id', 'id':'plylst_id'}, inplace=True)
train_data.head()

   plylst_id song_id  like_cnt
0      61281  525514        71
0      61281  129701        71
0      61281  383374        71
0      61281  562083        71
0      61281  297861        71

In [24]:
with open('../Datasets/song_meta.json', 'r', encoding='utf-8') as f:
    json_data = json.load(f)

In [25]:
song_data = pd.DataFrame(json_data)
song_data = song_data.drop(['artist_id_basket', 'artist_name_basket', 'song_gn_gnr_basket'], axis=1)
song_data.rename(columns={'id':'song_id', 'song_gn_dtl_gnr_basket':'genre'}, inplace=True)
song_data.head()

,genre,issue_date,album_name,album_id,song_name,song_id
0,[GN0901],20140512,불후의 명곡 - 7080 추억의 얄개시대 팝송베스트,2255639,Feelings,0
1,"[GN1601, GN1606]",20080421,"Bach : Partitas Nos. 2, 3 & 4",376431,"Bach : Partita No. 4 In D Major, BWV 828 - II....",1
2,[GN0901],20180518,Hit,4698747,Solsbury Hill (Remastered 2002),2
3,"[GN1102, GN1101]",20151016,Feeling Right (Everything Is Nice) (Feat. Popc...,2644882,Feeling Right (Everything Is Nice) (Feat. Popc...,3
4,"[GN1802, GN1801]",20110824,그남자 그여자,2008470,그남자 그여자,4

In [26]:
genre_list = []

for l in song_data['genre']:
    temp = dict()
    g = 0
    mx = 0
    
    for i in l:
        i = i[2:]
        n = int(i) // 100
        if n in temp:
            temp[n] += 1
        else:
            temp[n] = 1
    
    for i in temp:
        if mx < temp[i]:
            g = i
            mx = temp[i]
        elif mx == temp[i] and g > i:
            g = i
        
    genre_list.append(g)

song_data['genre'] = genre_list
song_data.head()

,genre,issue_date,album_name,album_id,song_name,song_id
0,9,20140512,불후의 명곡 - 7080 추억의 얄개시대 팝송베스트,2255639,Feelings,0
1,16,20080421,"Bach : Partitas Nos. 2, 3 & 4",376431,"Bach : Partita No. 4 In D Major, BWV 828 - II....",1
2,9,20180518,Hit,4698747,Solsbury Hill (Remastered 2002),2
3,11,20151016,Feeling Right (Everything Is Nice) (Feat. Popc...,2644882,Feeling Right (Everything Is Nice) (Feat. Popc...,3
4,18,20110824,그남자 그여자,2008470,그남자 그여자,4

In [27]:
merge = pd.merge(train_data, song_data)
merge.head(30)

,plylst_id,song_id,like_cnt,genre,issue_date,album_name,album_id,song_name
0,61281,525514,71,14,20130506,Hey Little Girl,2200223,Hey Little Girl
1,122798,525514,285,14,20130506,Hey Little Girl,2200223,Hey Little Girl
2,76836,525514,8,14,20130506,Hey Little Girl,2200223,Hey Little Girl
3,117966,525514,902,14,20130506,Hey Little Girl,2200223,Hey Little Girl
4,19623,525514,1,14,20130506,Hey Little Girl,2200223,Hey Little Girl
5,10853,525514,10,14,20130506,Hey Little Girl,2200223,Hey Little Girl
6,94159,525514,132,14,20130506,Hey Little Girl,2200223,Hey Little Girl
7,61281,129701,71,9,20130917,Brass,2201802,Octagon
8,122798,129701,285,9,20130917,Brass,2201802,Octagon
9,145788,129701,24,9,20130917,Brass,2201802,Octagon
10,61281,383374,71,10,19911021,Monsters Under The Bed,2216938,The Road
11,61281,562083,71,9,20000919,United,43227,Honeymoon
12,17297,562083,12,9,20000919,United,43227,Honeymoon
13,57947,562083,8,9,20000919,United,43227,Honeymoon
14,111406,562083,273,9,20000919,United,43227,Honeymoon
15,130590,562083,4180,9,20000919,United,43227,Honeymoon
16,93605,562083,3,9,20000919,United,43227,Honeymoon
17,140831,562083,2,9,20000919,United,43227,Honeymoon
18,32419,562083,21,9,20000919,United,43227,Honeymoon
19,141326,562083,4,9,20000919,United,43227,Honeymoon
20,42107,562083,3,9,20000919,United,43227,Honeymoon
21,25588,562083,2,9,20000919,United,43227,Honeymoon
22,90548,562083,280,9,20000919,United,43227,Honeymoon
23,10424,562083,438,9,20000919,United,43227,Honeymoon
24,102714,562083,30,9,20000919,United,43227,Honeymoon
25,1426,562083,1317,9,20000919,United,43227,Honeymoon
26,61281,297861,71,9,20050306,Back To Bedlam,303657,High
27,111541,297861,3,9,20050306,Back To Bedlam,303657,High
28,145672,297861,2,9,20050306,Back To Bedlam,303657,High
29,116010,297861,772,9,20050306,Back To Bedlam,303657,High

### 데이터 전처리 구상
like_cnt, 노래 등장 횟수, issue data를 기준으로 노래를 선정하고, 이를 기준으로 데이터를 정제한다.
1. like_cnt
- boxplot을 그린 후 1.5IQR로 기준 잡기
- 상한값 초과: like_cnt를 상한값으로 대체
- 하한값 미만: 노래 제거
2. 노래 등장 횟수
- 총 10회 이하로 나타나는 노래 제거
3. issue data
- 2019년 1월 1일 이전 출시된 노래 제거

### 예상 결과(전처리 없는 경우와 비교)
- like_cnt의 분포가 좀 더 정규분포에 가까워질 것으로 추정
- 등장 횟수가 많은 노래의 비중이 높아져 대중성 확보

### 추천 시스템 적용 결과